go.mod

Avoid dependency fetch failure due to invalid commit SHA
$ go get github.com/goto/optimus@main
go: github.com/goto/optimus@v0.0.0-20230303161721-4b02b6913cb8 requires
github.com/goto/optimus/sdk@v0.0.0-20230104081553-fa05355b2dda: invalid version: unknown revision fa05355b2dda

fix: bump github.com/goto/optimus/sdk commit SHA

---

core/scheduler/service/replay_service.go
core/scheduler/service/replay_service_test.go
core/scheduler/service/replay_worker.go
core/scheduler/service/replay_worker_test.go

Issues encountered:
1. Replay request created even though the namespace name is invalid.
2. Replay with sequential & parallel mode has its runs updated with the scheduler's state, even though the runs are not processed yet.

fix: replay issues

---

core/job/handler/v1beta1/job.go
core/job/handler/v1beta1/job_test.go
core/job/service/job_service.go
core/job/service/job_service_test.go

- Avoid doing query dry-run (generate jobs) for all the incoming jobs. Instead, only the newly added and modified ones.
- Adding job deletion check

feat: improve check job specs

---

core/job/handler/v1beta1/job.go
core/job/handler/v1beta1/job_test.go
core/job/service/job_service.go
core/job/service/job_service_test.go

* feat: only generate jobs for added and modified jobs when validating and check job deletion
* refactor: remove unused pointer receiver in JobService
* refactor: rename jobNamesWithValidationError to jobNamesWithInvalidSpec
* refactor: return unmodified specs from differentiateSpecs function in job service

feat: improve check job specs (#31)

---

ext/scheduler/airflow/__lib.py

Slack Job Failure Alerts should capture the task id of failed tasks

Fix: optimus job failure alerts 

---

internal/store/postgres/job/job_repository.go
internal/store/postgres/job/job_repository_test.go

When a job is updated and it no longer has any upstream, Optimus skipped the deletion of the upstream for the particular job. However, if at least 1 upstream left, the deletion of the rest of the upstream will work.

fix: unable to delete upstreams if no longer upstream found issue

---

ext/scheduler/airflow/dag/compiler_test.go
ext/scheduler/airflow/dag/dag.py.tmpl
ext/scheduler/airflow/dag/expected_dag.py
internal/store/postgres/scheduler/job_repository.go
internal/store/postgres/scheduler/job_repository_test.go

- Differentiate pools to limit slots for each task, hook, sensors.
- Fix missing run time config (currently, any job metadata is not being initialized to job details in scheduler context, thus any scheduler / resource config will not be compiled)

feat: differentiate pools for task, hook, sensors

---

ext/scheduler/airflow/__lib.py
ext/scheduler/airflow/dag/expected_dag.2.1.py
ext/scheduler/airflow/dag/expected_dag.2.4.py
ext/scheduler/airflow/dag/template/dag.2.1.py.tmpl
ext/scheduler/airflow/dag/template/dag.2.4.py.tmpl

fix incorrect arg `startup_timeout_in_secs` which is earlier passed to dag default args and pass it to kubernetespodoperator.
Note : Kubernetespodoperator explicitly cleans up the pod after the above timeout config.

fix : add k8s pod timeout in the operator instead of dag default args

---

client/cmd/playground/window/model.go
client/cmd/playground/window/window.go

On certain terminal (currently being confirmed on default terminal under MacOS), navigation for incrementing value does not work. The quickest update to address this issue is by providing additional key to act on the same result, like increment or decrement.

fix: playground window navigation not working

---

ext/store/bigquery/batch.go
ext/store/bigquery/batch_test.go

This PR is to include dataset name when there's error when validating it. The purpose is to make it easier to discover if there's error when a large number of data is being processed.

fix: update validation error to include dataset name for easier discovery

---

ext/scheduler/airflow/__lib.py
ext/scheduler/airflow/dag/expected_dag.2.1.py
ext/scheduler/airflow/dag/expected_dag.2.4.py
ext/scheduler/airflow/dag/expected_dag.2.6.py
ext/scheduler/airflow/dag/template/dag.2.1.py.tmpl
ext/scheduler/airflow/dag/template/dag.2.4.py.tmpl
ext/scheduler/airflow/dag/template/dag.2.6.py.tmpl

derive `schedule time` by `execution_date` in airflow 2.1.4

fix: DSTART on replay 

---

ext/store/bigquery/table.go
ext/store/bigquery/table_test.go

When updating an existing resource with type table in order to add cluster, there's a bug in a way the cluster is not applied. This PR attempts to fix this.

fix: bug updating table to add cluster is not reflected

---

core/scheduler/service/executor_input_compiler.go
core/scheduler/service/executor_input_compiler_test.go

This PR is to add labels from job spec, which are specified by the user, to the `JOB_LABELS` environment variables. This variable can then be used by the requiring plugins, like Transformers to add label for Big Query job.

feat: add labels from job spec to job labels environment

---

client/cmd/playground/window/constant.go
client/cmd/playground/window/model.go
client/cmd/playground/window/v1v2/constant.go
client/cmd/playground/window/v1v2/doc.go
client/cmd/playground/window/v1v2/model.go
client/cmd/playground/window/view.go
client/cmd/playground/window/window.go
docs/docs/concepts/intervals-and-windows.md

This PR is to add window playground v3. Version 3 is the main version of playground. Version 1 and version 2 are moved to another package. In order to activate the version 1 and version 2 mode, the user needs to use flag `--v1-v2` when executing playground. Example:
```zsh
optimus playground window
opitmus playground window --v1-v2
```

feat: window playground v3

---

core/job/handler/v1beta1/job_adapter.go
core/job/spec.go
core/job/spec_test.go
internal/store/postgres/job/adapter.go

Retry delay is configurable through the job specification file (`behavior.retry.delay`) or the scheduler's project variables (`dag_retry_delay_in_secs`). If both are configured, then the value that is configured in job specification file will be prioritized.
A bug encountered the config is set in both of the places, however the value is job specification file is ignored.
Sample job specification file:
```yaml
behavior:
depends_on_past: False
retry:
count: 10
exponential_backoff: false
delay: 10m
```
Expectation in DAG file:
```python
DAG_RETRY_DELAY = int(Variable.get("dag_retry_delay_in_secs", default_var=5 * 60))
default_args = {
...
"retry_delay": timedelta(seconds=600),
...
}
```
Current DAG file result:
```python
DAG_RETRY_DELAY = int(Variable.get("dag_retry_delay_in_secs", …
```

fix: retry delay in jobspec ignored issue

---

config.sample.yaml
config/config_server.go
core/scheduler/service/replay_service.go
core/scheduler/service/replay_service_test.go
optimus.sample.yaml
server/optimus.go

Add a functionality in CreateReplay to read `REPLAY_EXECUTION_PROJECT` & `ALLOWED_EXECUTION_PROJECTS` config value from namespace-level & project-level config. This in turn adds a new config key stored in namespace & project.
Nevertheless we will still allow execution project override by providing replay job config in the command.
```yaml
version: 1
log:
level: INFO
format: ""
host: localhost:9200
project:
name: test-optimus-ahmad
config:
allowed_execution_projects: pilotdata-integration,data-test
replay_execution_project: pilotdata-integration
namespaces:
- name: test_namespace_ahmad
config:
replay_execution_project: pilotdata-integration-specific
job:
path: test_namespace_ahmad/jobs
datastore:
- type: bigquery
path: test_namespace_ahmad/resources
backup: {}
```

feat: replay decentralization - provide execution project as namespace & project level config

---

ext/store/bigquery/bigquery.go
ext/store/bigquery/bigquery_test.go
ext/store/bigquery/client.go
ext/store/bigquery/client_test.go
ext/store/bigquery/routine.go
ext/store/bigquery/routine_test.go
ext/store/bigquery/schema.go
go.mod

- support job validation depends on [Routine](https://cloud.google.com/bigquery/docs/routines#:~:text=In%20BigQuery%2C%20routines%20are%20a,Table%20functions.) in BigQuery datastore
- Routine is including User Defined Functions, Table Function, Store Procedure

feat: support routine bigquery on job validation

---

client/cmd/apply/apply.go

Increase timeout for `optimus apply` command from 5 mins to 60 mins, to support large changes

fix: increase timeout in optimus apply to 60mins

---

client/cmd/job/validate.go

Increase timeout for `optimus job validate` command's server side calls from 15 mins to 60 mins, to support large changes

fix: increase timeout in optimus job validate to 60mins

---

client/cmd/job/plan.go

- before this changes, job migrate plan are not logged
- this changes will logged job migrate plan properly when verbose flag are set

fix: plan migrate job log verbose

---

core/scheduler/job.go
core/scheduler/job_run.go
core/scheduler/replay.go
core/scheduler/service/replay_service.go
core/scheduler/service/replay_worker.go
core/scheduler/service/replay_worker_test.go
ext/notify/alertmanager/adapter.go
server/optimus.go

Support replay lifecycle events like 
1. created
2. timeout 
3. success 
4. canceled 
5. failed

Feat: add replay lifecycle events

---

core/resource/handler/v1beta1/resource.go
core/resource/resource.go
core/resource/resource_test.go
core/resource/service/resource_service.go
core/resource/service/resource_service_test.go
ext/store/bigquery/backup.go
ext/store/bigquery/bigquery.go
ext/store/bigquery/bigquery_test.go
ext/store/bigquery/dataset_spec.go
ext/store/bigquery/dataset_spec_test.go
internal/store/postgres/resource/repository.go
internal/store/postgres/resource/repository_test.go

Add a new support for Resource Spec V2 in Optimus, which conceptually separates **Optimus resource name** from the actual name used to create the reosurce in respective datastore (for now, BigQuery).
Example:
```
version: 2
name: mart.namespace.table
type: table
labels:
example: label
spec:
project: warehouse-mart
dataset:  namespace_specific
name: table
schema:
- mode: NULLABLE
name: event_timestamp
type: DATE
- mode: NULLABLE
name: uuid
type: STRING
```
the Optimus resource name is:`mart.namespace.table`, meanwhile the name of the table in bigquery will be: `warehouse-mart.namespace_specific.table`

feat: support resource spec v2

---

ext/scheduler/airflow/airflow.go
ext/scheduler/airflow/airflow_test.go

For every calls to `scheduler.DeployJobs()`, `__lib.py` will be uploaded once for every project. Approach is using sync.Map to store a map of flags, which key is Optimus project name & flag marks if the lib is already uploaded

fix: Only upload lib.py once for every project

---

core/tenant/project.go
ext/scheduler/airflow/__lib.py
ext/scheduler/airflow/dag/compiler.go
ext/scheduler/airflow/dag/models.go
ext/scheduler/airflow/dag/template/dag.2.1.py.tmpl
ext/scheduler/airflow/dag/template/dag.2.4.py.tmpl
ext/scheduler/airflow/dag/template/dag.2.6.py.tmpl
ext/scheduler/airflow/dag/template/dag.2.9.py.tmpl

Add a new tenant config, `DISABLE_JOB_SCHEDULING`, which can be set to `"true"` if there's a need to remove job schedule interval in Airflow. This way, all jobs on the project can only run on **manual trigger** OR **replay**.
Note that while schedule interval is disabled through Airflow, schedule interval will still be present on job specs.

feat: enable tenant option to disable job scheduling

---

core/scheduler/service/deployment_service.go
core/scheduler/service/deployment_service_test.go

Currently refresh command is blocked if there is a partial upstream resolution issue (static dependency).

fix: avoid refresh being blocked due to partial resolve upstream issue

---

core/scheduler/service/deployment_service.go
core/scheduler/service/deployment_service_test.go

Currently, the job refresh command is blocked if there is a partial upstream resolution issue (static dependency).

fix: blocked job refresh issue

---

ext/store/maxcompute/client.go
ext/store/maxcompute/client_test.go
ext/store/maxcompute/masking_policy.go
ext/store/maxcompute/masking_policy_test.go
ext/store/maxcompute/maxcompute.go
ext/store/maxcompute/maxcompute_test.go
ext/store/maxcompute/schema.go
ext/store/maxcompute/schema_test.go
ext/store/maxcompute/table.go
ext/store/maxcompute/table_test.go
ext/store/maxcompute/wrapper.go
internal/utils/contains.go
internal/utils/contains_test.go

**Description**
Add a new functionality in Optimus Maxcompute resource management, specifically on the Maxcompute table creation, to apply data masking policy in the table columns.
**Spec Example**
Resulting spec supported for this functionality can be seen here:
```yaml
version: 2
name: maxcompute_project.schema.example_table
type: table
spec:
description: This is a sample MaxCompute table
project: maxcompute_project
database: schema
name: example_table
schema:
- name: order_id
type: string 
- name: order_name
type: string
mask_policy: example_masking_mask_policy
unmask_policy: example_masking_unmask_policy
- name: order_timestamp
type: timestamp
- name: order_date
type: date
- name: order_customer
type: string
mask_policy: customer_name_mask_policy
unmask_policy: …
```

feat: add apply masking policy function to maxcompute table

---

client/cmd/internal/plan/operation_namespace.go
client/cmd/job/plan.go
client/cmd/resource/plan.go

This fixes the ongoing bugs when specs are just created/deleted. Instead of returning error, treat it as empty spec but skip it in the optimus plan file generator.

fix: treat empty file as empty specs, skip empty names in optimus plan

---

core/job/service/job_service.go

Force pass job source validation when the upstream resources are not found in both DB & store, as part of quick-fix for `optimus job validate` usecase.
This force-pass logic was made because of the query parser used to generate Upstream URN was mistakenly extracts 3-level nested struct columns (e.g. `x.y.z`, where `x` is the base column) as upstream tables. Since modifying the regex or any method to detect upstream may take long time, this approach is done.

chore: force pass job validate on resource nonexistence in db & store
