goto/optimus

client/cmd/scheduler/upload_all.go
core/scheduler/handler/v1beta1/job_run.go
core/scheduler/handler/v1beta1/job_run_test.go
ext/scheduler/airflow/airflow.go

Co-authored-by: Yash Bhardwaj <imyashbhardwaj@gmail.com>

fix: make upload to scheduler async

---

core/event/job.go
core/job/handler/v1beta1/job.go
core/job/handler/v1beta1/job_adapter.go
core/job/service/job_service.go
core/job/service/job_service_test.go
server/optimus.go

feat: publish job events

---

core/job/resolver/upstream_resolver.go
core/job/service/job_service.go
ext/scheduler/airflow/airflow.go

Reducing the limits to control spike in memory consumption.

refactor: reduce concurrency limits for some api

---

internal/store/postgres/scheduler/job_repository.go
internal/store/postgres/scheduler/job_repository_test.go

creating this PR to make [this PR](https://github.com/goto/optimus/pull/4) available in main branch

fix: job scheduling configs not match

---

ext/scheduler/airflow/dag/dag.py.tmpl
ext/scheduler/airflow/dag/expected_dag.py

creating this PR to make [this PR](https://github.com/goto/optimus/pull/6) available in main branch

fix: disable depends_on_past for sensors and hooks

---

client/cmd/scheduler/upload_all.go
core/scheduler/handler/v1beta1/job_run.go
core/scheduler/handler/v1beta1/job_run_test.go
ext/scheduler/airflow/airflow.go

creating this PR to make [this PR](https://github.com/goto/optimus/pull/13) available in main branch

fix: upload to scheduler async

---

core/resource/service/resource_manager.go
core/resource/service/resource_manager_test.go
core/resource/service/resource_service.go
core/resource/service/resource_service_test.go
server/optimus.go

creating this PR to make [this commit](https://github.com/goto/optimus/commit/159d1ceb846f4cf3fa80f40f3a455417b64dfdf5#diff-625743f118a9f2feec2148564e3bea953ed8438835e4d7f654c5f48063c9d483) available in main branch

fix: do not return error in case resource already exists

---

core/job/service/job_service.go
core/job/service/job_service_test.go
core/job/spec.go
core/job/spec_test.go

feat: job downstream deletion

---

client/cmd/playground/window/model.go
client/cmd/playground/window/window.go

This PR is to address issue in window with playground.
* window version 2 results sometime are not shown
* offset and size is sometime getting updated together
Another update as well.
* refactor to remove unnecessary implementation
* refactor to align table input

fix: window with playground

---

core/scheduler/replay.go
core/scheduler/replay_test.go
core/scheduler/service/replay_validator.go
core/scheduler/service/replay_validator_test.go
core/scheduler/service/replay_worker.go
core/scheduler/service/replay_worker_test.go
ext/scheduler/airflow/airflow.go
server/optimus.go

feat: capability to create runs on replay

---

core/job/handler/v1beta1/job.go
core/job/job.go
core/job/service/job_service.go
core/resource/handler/v1beta1/resource.go
core/scheduler/event.go
core/scheduler/service/job_run_service.go
core/scheduler/service/replay_service.go
core/scheduler/service/replay_worker.go
ext/scheduler/airflow/airflow.go

- changelog metrics of jobs (add/update/delete)
- upstream refresh metrics
- dag upload/removal metric
- enrich resource upload metrics
- enrich scheduler events metrics
- add job start metric
- enrich/add long-running features duration metrics (job replace-all, validation, refresh, resource upload-all)
- add replay request metric

feat: publish missing metrics

---

client/cmd/replay/create.go
core/scheduler/handler/v1beta1/replay.go
core/scheduler/replay.go
core/scheduler/replay_test.go
core/scheduler/service/replay_worker.go
core/scheduler/service/replay_worker_test.go
core/scheduler/status.go
core/scheduler/status_test.go

feat: improve user experience replay

---

core/job/service/job_service.go
core/job/service/job_service_test.go
core/job/spec.go
core/job/spec_test.go
ext/scheduler/airflow/dag/dag.py.tmpl

feat: job spec name validation

---

internal/telemetry/prometheus.go

Fixing issue due to concurrent read/write in metric map.

fix: concurrent read write issue in metric map

---

ext/scheduler/airflow/airflow.go
ext/scheduler/airflow/client.go

* fix: airflow client api
* fix: api endpoint error message

fix: airflow client api (#86)

---

client/cmd/namespace/register.go
client/cmd/project/register.go
client/cmd/resource/create.go

fix: config load on client

---

.github/workflows/release.yml
.goreleaser.yml

Adapting to the GoReleaser changes in v0.9.5

fix: update goreleaser

---

core/scheduler/service/job_run_service.go
core/scheduler/service/job_run_service_test.go
ext/scheduler/airflow/__lib.py
server/optimus.go

This PR is to address issue when getting interval.

fix: issue when getting interval

---

core/job/service/plugin_service.go
ext/store/bigquery/resource_urn.go

NB: just PR for uncommitted changes in my local. following up with the [previous PR](https://github.com/goto/optimus/pull/127)

fix: unprocessed resource urn on bq extractor

---

client/cmd/job/change_namespace.go

* fix: perform namespace File migration via export

fix: namespace migration via export (#135)

---

core/job/service/job_service.go

fix: only check cyclic dependencies for the modified or newly added jobs

Perf : Optimus Validate

---

ext/scheduler/airflow/dag/compiler_test.go
ext/scheduler/airflow/dag/expected_dag.2.1.py
ext/scheduler/airflow/dag/expected_dag.2.4.py
ext/scheduler/airflow/dag/expected_dag.2.6.py
ext/scheduler/airflow/dag/template/dag.2.1.py.tmpl
ext/scheduler/airflow/dag/template/dag.2.4.py.tmpl
ext/scheduler/airflow/dag/template/dag.2.6.py.tmpl

This is to fix compilation issue when a job has description with new line (the next lines were not properly commented)

fix: description with new line compilation issue

---

ext/scheduler/airflow/__lib.py

Adding the fix for https://github.com/goto/optimus/issues/147
* As the optimus request timout is not airflow DAG specific, Added this as a global config for all dags.

fix: add optimus request timeout config

---

plugin/plugin_service.go
plugin/plugin_service_test.go
plugin/yaml/tests/sample_plugin_with_parser_and_destination_template.yaml

bring back the fix from this commit https://github.com/goto/optimus/pull/164/files

fix: ignore destination

---

client/cmd/job/run_input.go

fix improper implementation from PR https://github.com/goto/optimus/pull/172/files#diff-f78641fec156152384bb46d1916c464c328e8a70839774a710c5a5abdaf81d59R159

fix: secret sourcing

---

client/cmd/job/change_namespace.go

This PR fix the way how to load config on `job change-namespace` command

fix: config load on job change-namespace

---

internal/lib/window/config.go
internal/lib/window/custom.go
internal/lib/window/custom_test.go

This is to fix issue on window v3 where size can be set to negative.

fix: window v3 size implementation

---

core/scheduler/service/job_run_service.go
core/scheduler/service/job_run_service_test.go

This PR is to address the issues when calculating window interval.

fix: issue when calculating window interval

---

config.sample.yaml
config/config_server.go
ext/scheduler/airflow/dag/compiler.go
ext/scheduler/airflow/dag/compiler_test.go
ext/scheduler/airflow/dag/expected_dag.2.1.py
ext/scheduler/airflow/dag/expected_dag.2.4.py
ext/scheduler/airflow/dag/expected_dag.2.6.py
ext/scheduler/airflow/dag/models.go
ext/scheduler/airflow/dag/template/dag.2.1.py.tmpl
ext/scheduler/airflow/dag/template/dag.2.4.py.tmpl
ext/scheduler/airflow/dag/template/dag.2.6.py.tmpl
optimus.sample.yaml
server/optimus.go
server/scheduler.go
server/server.go

* fix: split the grpc and http server port for optimus
* fix: fix lint errors
* fix: fix ingress host grpc
* chore: update the config

fix: split the grpc and http server port for optimus (#193)

---

config/loader.go
ext/notify/alertmanager/alertManager.go
ext/notify/alertmanager/alertManager_test.go
server/optimus.go

* fix: add better logging for alert manager

fix: add better logging for alert manager (#206)

---

client/cmd/job/deploy.go
client/cmd/job/job.go

New command will be introduced:
```
- optimus job deploy [--jobs jobA,jobB] [--namespace sample_namespace]
```
Approach:
```
- Use GetJobSpecifications, AddJobSpecifications, UpdateJobSpecifications API
- Add/Update will be based on the Get response
```

feat: add job deploy command

---

client/cmd/job/replace_all.go
client/cmd/resource/upload_all.go

- add visibility to know root cause of EOF issue
- https://github.com/grpc/grpc-go/blob/fa274d77904729c2893111ac292048d56dcf0bb1/stream.go#L114

feat: add client handle catch error on stream.Send EOF

---

client/cmd/internal/plan/operation_namespace.go
client/cmd/internal/plan/plan_test.go
client/cmd/internal/plan/resource.go

- handle move directory within same namespace
- handle resource plan different datastore

feat: improve migration handling

---

core/job/job.go
core/job/job_test.go
core/job/service/job_service.go
core/job/service/job_service_test.go

feat: support auto deps when destination job is changed

---

internal/store/postgres/scheduler/replay_repository.go
internal/store/postgres/scheduler/replay_repository_test.go

To reproduce the bug:
1. Create replay with job-config `DRY_RUN=true`
2. Once the first replay is finished, create another replay (same table, same date), but without job-config set
3. We can see in the `replay_request` table, that the `config` value is empty. However, the run in Airflow will show `DRY_RUN=true` in the log.
This fix is to only fetch the last replay job config and only if the status is `in_progress`.

fix: replay config unchanged given for the same run issue

---

ext/store/bigquery/bigquery.go
ext/store/bigquery/bigquery_test.go
ext/store/bigquery/client.go
ext/store/bigquery/model.go
ext/store/bigquery/model_test.go
ext/store/bigquery/schema.go

- Resource: [BigQuery Model](https://cloud.google.com/bigquery/docs/bqml-introduction)

feat: add bq model resource on job validate

---

config/config_server.go
core/scheduler/job_run.go
core/scheduler/larkEvent.go
core/scheduler/service/events_service.go
core/tenant/secret.go
ext/notify/lark/lark.go
ext/notify/lark/lark_test.go
ext/notify/slack/slack.go
go.mod
go.sum
server/optimus.go

Adding the commits for the Lark integration with Optimus
Below are the changes:
Lark.go File which includes the message builder and send worker function

Lark notification Integration with optimus

---

core/scheduler/job.go
core/scheduler/job_run.go
core/scheduler/replay.go
core/scheduler/service/replay_service.go
core/scheduler/service/replay_worker.go
core/scheduler/service/replay_worker_test.go
ext/notify/alertmanager/adapter.go
server/optimus.go

Feat: add replay lifecycle events (#271)

---

internal/store/postgres/migrations/000065_cancel_abandoned_replays.down.sql
internal/store/postgres/migrations/000065_cancel_abandoned_replays.up.sql

* fix: handle old abandoned replay requests
* fix: handle old abandoned replay requests

fix: handle old abandoned replay requests (#290)

---

core/scheduler/service/replay_service.go
core/scheduler/service/replay_service_test.go
core/scheduler/service/replay_worker.go
core/scheduler/service/replay_worker_test.go
internal/store/postgres/scheduler/replay_repository.go

* fix: handle replay heartbeat bug

fix: handle replay heartbeat bug (#292)

---

core/scheduler/service/deployment_service_test.go
core/scheduler/service/job_run_service.go
core/scheduler/service/job_run_service_test.go
plugin/plugin_service.go
plugin/upstream_identifier/parser/query_parser.go
plugin/upstream_identifier/processor/query_clean_up.go
plugin/upstream_identifier/processor/query_clean_up_test.go
server/optimus.go

feat: clean query assets before execution

---

core/scheduler/service/replay_validator.go
core/scheduler/service/replay_validator_test.go

Fixing issue on replay to allow this case:
job end date: 2024-11-05
job interval: daily
replay end date: 2024-11-06
above case should be valid because job end date represents the logical date, while replay represents the scheduled date.

fix: replay end time validation issue (main)

---

ext/store/maxcompute/external_table.go
ext/store/maxcompute/schema.go
ext/store/maxcompute/schema_test.go
ext/store/maxcompute/table.go
ext/store/maxcompute/table_spec.go
ext/store/maxcompute/table_test.go
ext/store/maxcompute/view.go
ext/store/maxcompute/view_spec.go
ext/store/maxcompute/view_spec_test.go
ext/store/maxcompute/view_test.go
go.mod
go.sum

- implement auto partition feature
- support common and transactional table
- integrate view table with golang SDK

Integrate golang sdk

---

ext/store/maxcompute/table.go
ext/store/maxcompute/table_spec.go
ext/store/maxcompute/table_test.go

**Summary**
Add support for adding table properties (TBLPROPERTIES) to create/update a table in maxcompute.

feat: support tblproperties in maxcompute tables

---

ext/store/maxcompute/client.go
ext/store/maxcompute/external_table.go
ext/store/maxcompute/external_table_test.go
ext/store/maxcompute/masking_policy.go
ext/store/maxcompute/masking_policy_test.go
ext/store/maxcompute/maxcompute.go
ext/store/maxcompute/maxcompute_test.go
ext/store/maxcompute/table.go
ext/store/maxcompute/table_test.go

Add new functionality to bind maxcompute masking policies to external table specs.

feat: apply masking policy to maxcompute external tables

---

client/cmd/apply/apply.go
client/cmd/internal/plan/job.go
client/cmd/internal/plan/kind.go
client/cmd/internal/plan/resource.go
client/cmd/job/plan.go
client/cmd/resource/plan.go
client/local/specio.go
client/local/specio/job_spec_io.go
client/local/specio/job_spec_io_test.go
client/local/specio/resource_spec_io.go
client/local/specio/resource_spec_io_test.go

fix error for resource plan
use strict instead
remove debug lines
fix reference
provide path in plan & apply only provided paths
upgrade to use yaml.v3
apply ReadByDirPath for all
add tests

chore: fail optimus plan if yaml is malformed

---

ext/store/maxcompute/external_table.go
ext/store/maxcompute/external_table_test.go
ext/store/maxcompute/sheet_sync.go

feat: add support for  implicit role assumption serde property for external tables

---

config/config_server.go
config/loader_test.go
core/job/job.go
core/resource/resource.go
core/scheduler/job_run.go
core/scheduler/service/events_service.go
core/scheduler/service/events_service_test.go
core/scheduler/service/replay_service.go
core/scheduler/service/replay_service_test.go
core/scheduler/service/replay_worker.go
core/scheduler/service/replay_worker_test.go
core/tenant/project.go
ext/notify/alertmanager/adapter.go
ext/notify/alertmanager/alertManager.go
ext/notify/alertmanager/alertManager_test.go
server/optimus.go

- add tenant config alertmanager endpoint override
- add server config enable alertmanager

feat: add tenant level config alertmanager destination

---

ext/store/maxcompute/masking_policy.go

1. Publish masking policy metrics in form of prometheus metrics named `masking_policy_action_status` for every failure/success in bind/unbind of masking policy in tables
2. Fix error log to use `logger.Error` instead of `logger.Info`

chore: publish masking policy metrics

---

client/cmd/apply/apply.go

- handle resource apply when failure in update in manager https://github.com/goto/optimus/blob/d5e59c58d112d8b1b5eba96abda31c138f75bc4f/core/resource/service/resource_manager.go#L82

feat(client): add handle resource apply on apply command

---

core/job/service/job_service.go
core/job/service/job_service_test.go
core/tenant/tenant.go

chore: resolve downstream dependency on force delete job
